services:
    progress.listener:
        class: UAM\Bundle\MaintenanceBundle\EventListener\WarningRequestListener
        arguments:
            - @router
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
