services:
    warning.listener:
        class: UAM\Bundle\MaintenanceBundle\EventListener\WarningRequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }