services:
    maintenance.listener:
        class: UAM\Bundle\MaintenanceBundle\EventListener\MaintenanceListener
        arguments:
            [@router, @service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: %uam_maintenance.listener.priority% }
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
